default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  database: ibge_codmun_development
test:
  <<: *default
  database: ibge_codmun_test
production:
  <<: *default
  database: ibge_codmun_production
  username: ibge_codmun
  password: <%= ENV['IBGE_CODMUN_DATABASE_PASSWORD'] %>
